// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkvI-7829xd3LYde27cp2Q9WZZYJDUJ38',
    appId: '1:127152031834:web:b6b92a3c1f47e386ecf063',
    messagingSenderId: '127152031834',
    projectId: 'clouds-27fbf',
    authDomain: 'clouds-27fbf.firebaseapp.com',
    storageBucket: 'clouds-27fbf.appspot.com',
    measurementId: 'G-LT00TEH46M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAUlO-Y4kK4_zw7G3EyT8SqTMrN5o3KjI',
    appId: '1:127152031834:android:917a8f065680e2f2ecf063',
    messagingSenderId: '127152031834',
    projectId: 'clouds-27fbf',
    storageBucket: 'clouds-27fbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4sQAigCIR6IyHSTHeVaFUWVjTOJFabn8',
    appId: '1:127152031834:ios:7ab667081eaf2197ecf063',
    messagingSenderId: '127152031834',
    projectId: 'clouds-27fbf',
    storageBucket: 'clouds-27fbf.appspot.com',
    iosClientId: '127152031834-pqgao7dkodbr1qfnnjsm411njnatohgj.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFunctions',
  );
}
